// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using whiteboard_app_data.Data;

#nullable disable

namespace whiteboard_app_data.Migrations
{
    [DbContext(typeof(WhiteboardDbContext))]
    partial class WhiteboardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("whiteboard_app_data.Models.Canvas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("Name");

                    b.HasIndex("ProfileId");

                    b.ToTable("Canvases");
                });

            modelBuilder.Entity("whiteboard_app_data.Models.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultCanvasHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultCanvasWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultFillColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultStrokeColor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultStrokeThickness")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("whiteboard_app_data.Models.Shape", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CanvasId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FillColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerializedData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ShapeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrokeColor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<double>("StrokeThickness")
                        .HasColumnType("REAL");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanvasId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsTemplate");

                    b.HasIndex("ShapeType");

                    b.HasIndex("IsTemplate", "TemplateName")
                        .HasFilter("[IsTemplate] = 1 AND [TemplateName] IS NOT NULL");

                    b.ToTable("Shapes");

                    b.HasDiscriminator<int>("ShapeType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("whiteboard_app_data.Models.ShapeConcrete", b =>
                {
                    b.HasBaseType("whiteboard_app_data.Models.Shape");

                    b.HasDiscriminator().HasValue(0)  // Line
                        .HasValue(1)  // Rectangle
                        .HasValue(2)  // Oval
                        .HasValue(3)  // Circle
                        .HasValue(4)  // Triangle
                        .HasValue(5); // Polygon
                });

            modelBuilder.Entity("whiteboard_app_data.Models.Canvas", b =>
                {
                    b.HasOne("whiteboard_app_data.Models.Profile", "Profile")
                        .WithMany("Canvases")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("whiteboard_app_data.Models.Shape", b =>
                {
                    b.HasOne("whiteboard_app_data.Models.Canvas", "Canvas")
                        .WithMany("Shapes")
                        .HasForeignKey("CanvasId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Canvas");
                });

            modelBuilder.Entity("whiteboard_app_data.Models.Canvas", b =>
                {
                    b.Navigation("Shapes");
                });

            modelBuilder.Entity("whiteboard_app_data.Models.Profile", b =>
                {
                    b.Navigation("Canvases");
                });
#pragma warning restore 612, 618
        }
    }
}
